# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160307_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='level',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
